apiVersion: v1
kind: Pod
metadata:
  name: site
spec:
  containers:
  - name: site
    image: nginx
    resources:
      limits:
        memory: "48Mi"
      requests:
        memory: "32Mi"
    ports:
      - containerPort: 80