apiVersion: v1
kind: Pod
metadata:
  name: site
spec:
  containers:
  - name: teste-site
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        #cpu: "500m"
    ports:
      - containerPort: 80
